spring:
  application:
    name: api-gateway
server:
  port: 8090
  
  
zuul:
  routes:
    productos:
     service-id: servicio-producto
     path: /api/productos/**
     url: http://producto:8880
    items:
      service-id: servicio-item
      path: /api/items/**
      url: http://item:8081
    usuarios:
      service-id: servicio-usuario
      path: /api/users/**           
      url: http://usuario:8082
    security:
      service-id: servicio-oauth
      path: /api/security/**           
      url: http://oauth:9100
      sensitive-headers:
      - Cookie
      - Set-Cookie      
